version: "3.4"

services:
  api:
    image: azsdkdemoapi
    env_file: .env
    volumes: 
      - "${HOME}/.azure:/root/.azure"
    expose:
       - 80
    ports:
      - "5051:80"
    build:
      context: src/api/
      dockerfile: Dockerfile
  processor:
    image: azsdkdemoprocessor
    env_file: .env
    volumes: 
      - "${HOME}/.m2:/root/.m2"
      - "${HOME}/.azure:/home/developer/.azure"
    build:
      context: src/processor/
      dockerfile: Dockerfile
