# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: "3.7"

services:
  azsdkdemonetwebapp:
    image: ${CONTAINER_REGISTRY_NAME}/azsdkdemonetwebapp
    build:
      context: .
      dockerfile: WebApp/Dockerfile
    depends_on:
      - azsdkdemonetapi
    ports:
      - 1080:80
      - 1443:443
  azsdkdemonetapi:
    image: ${CONTAINER_REGISTRY_NAME}/azsdkdemonetapi
    env_file: ../../.env
    volumes: 
        - "~/.azure:/root/.azure"
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
      - 2080:80
      - 2443:443
  azsdkdemonetqueueservice:
    image: ${CONTAINER_REGISTRY_NAME}/azsdkdemonetqueueservice
    env_file: ../../.env
    volumes: 
        - "~/.azure:/root/.azure"
    build:
      context: .
      dockerfile: Services/QueueService/Dockerfile
  # azsdkdemonetfunctions:
  #   image: ${CONTAINER_REGISTRY_NAME}/azsdkdemonetfunctions
  #   env_file: ../../.env
  #   volumes: 
  #       - "~/.azure:/root/.azure"
  #   build:
  #     context: .
  #     dockerfile: Services/Functions/Dockerfile
  #   ports:
  #     - 3080:80
  #     - 3443:443
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - 10000:10000
      - 10001:10001
