kind: ConfigMap
metadata:
  name: websettings
apiVersion: v1
data:
  appsettings.json: |-
    {
        "API_ENDPOINT": "http://52.156.73.84",
        "FUNCTIONS_ENDPOINT": "http://memealyzerprodfunction.azurewebsites.net"
    }
